---
- name: configura maquina web com django
  hosts: web
  user: ubuntu
  become_user: root
  gather_facts: False
  become: true

  pre_tasks:
    - name: Apt update
      raw: sudo apt -y update

    - name: Install python for Ansible
      raw: sudo apt install -y python python-dev

  tasks:
    - name: Cria usuario da aplicacao
      user:
        name: django

    - name: Instala pacotes do python e django
      apt:
        name: python3-dev python3-django
